name: linux-on-litex-vexriscv
channels:
  - litex-hub
dependencies:
  - dtc
  - gcc-riscv32-elf-nostdc
  - gdb-riscv32-elf
  - nextpnr-ecp5
  - openocd
  - verilator
  - libevent
  - json-c
  - yosys
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
